%YAML:1.0
BaseConfig:
  minDetectorConfidence: 0.25
  minTrackerConfidence: 0.2
  minMatchingScore4Overall: 0.3
  minTrailingKeyPtsForReidExtraction: 10
  gpuId: 0

TargetManagement:
  maxTargetsPerStream: 50
  enableBboxUnclipping: 1

TrajectoryManagement:
  useUniqueID: 1

ReIDModule:
  enable: 1